name: machine_learning
channels:
- defaults
dependencies:
- holoviews=1.8.3
- matplotlib=2.1.0
- numpy=1.13.3
- pandas=0.20.3
- param=1.5.1
- scipy=0.19.1
- seaborn=0.8.0
- setuptools=36.5.0
- statsmodels=0.8.0
- pip:
  - paramnb==2.0.2

