name: py34_ml
channels:
- defaults
dependencies:
  - python=2.7
  - holoviews
  - matplotlib
  - numpy
  - pandas
  - param
  - seaborn
  - pip:
    - git+https://github.com/ioam/paramnb#egg=paramnb[complete]

