name: py34_ml
channels:
- defaults
dependencies:
  - python=3.4
  - bokeh=0.12.4
  - scipy=0.19.0
  - matplotlib=2.0.1
  - datashader=0.4.0
  - param=1.4.2=py34_0
  - scikit-learn=0.18.1
  - notebook=4
  - holoviews=1.6.2=py34_0
  - pip:
    - git+https://github.com/ioam/paramnb.git#egg=paramnb

